server:
  port: 8080  #默认端口号
spring:
  #配置数据库
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  #配置redis
  data:
    redis:
      host: localhost
      port: 6379

  #JSON输出格式优化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

qwen:
  api-key: sk-004ece4675b742f1b0df4b8b1be6169a
  api-url: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions #通义千问


logging:
  level:
    root: info
